# Generated by Django 2.2.3 on 2019-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_rating',
            field=models.IntegerField(blank=True),
        ),
    ]
