# Generated by Django 2.2.3 on 2019-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190722_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, through='movie.ActMovRel', to='movie.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
