# Generated by Django 2.2.3 on 2019-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190725_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
