# Generated by Django 2.2.3 on 2019-07-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
